### ISSUE TITLE
Long Standing Issue: Add Data to Existing Categories

### ISSUE THREAD

**Issue by gabrielbarker** [gabrielbarker/qual-id#1]
## Long Standing Issue: Add values to the existing qual-id categories

_Note: Any number of people can work on this issue, so it will remain open and won't be assigned. If you'd like to comment with any info on what you're going to work on, that would be helpful to stop people doing the same thing, but it's up to you._

This involves adding strings to a list in a python class. It will be a very simple, yet impactful enhancement. Additional details can be found in CONTRIBUTING.md. Also check out [this PR](https://github.com/gabrielbarker/qual-id/pull/3) for a good example.

_Contributions from beginners are very welcome!_

**Comment by chouhanaryan** [comment]
HI, I'd like to work on this for Hacktoberfest 😃

**Comment by tanya4067** [comment]
Hi, I'd like to contribute to it

**Comment by mephi007** [comment]
Hey @gabrielbarker, I would like to contribute on this, can you please assign this to me?

**Comment by srshobhit72** [comment]
Hey @gabrielbarker, I would like to contribute on this, can you please assign this to me?

**Comment by gabrielbarker** [comment]
@chouhanaryan @tanya4067 @mephi007 

I've updated the issue description to say that basically this issue will never be 'closed', and so all of you are encouraged to contribute. I won't assign anyone to this so as not to discourage others

_Thank you guys for being interested in this, I can't wait to see what you contribute!_

Also if you have any suggestions on a better way to manage this project then I'm all ears

**Comment by mephi007** [comment]
hey @gabrielbarker raised PR #7 for issue #2.

**Comment by christya95** [comment]
Hey @gabrielbarker, this is my first Hackathon and I was wondering if I could contribute to this issue ?

**Comment by gabrielbarker** [comment]
Closing this issue and reopening with a clone so that people can continue to find this repo during Hacktoberfest
